ARG SENTRY_IMAGE
FROM ${SENTRY_IMAGE}
#https://medium.com/sentry-with-docker/installing-sentry-with-docker-c1d83dfee577

#COPY entrypoint.sh /entrypoint.sh
#
#RUN chmod +x /entrypoint.sh
#
#ENTRYPOINT ["/entrypoint.sh"]
